package models.enums;

/**
 * Configuration enum
 */
public enum CONFIG {
    PROVIDERS, BATCH_SIZE, SERVICES, MUTATION_PROB, CROSSOVER_PROB, CROSSOVER_POINTS, POPULATION, ELITE_COUNT,
    MUTATOR_TYPE, SPLIT_PARALLELS, CONVERGENCE, SHOW_RESULTS, TIME_LIMIT, SLOPE, EVOLUTION, SURVIVORS_SIZE, STEADY_GENERATIONS, PRINTS
}

